# Generated by Django 3.2.23 on 2024-01-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vip',
            field=models.BooleanField(default='False'),
        ),
    ]
